/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.org.sparks_of_fabrication.imgstenography.graphics;

import com.github.org.sparks_of_fabrication.imgstenography.loaders.ImageLoader;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.plaf.FileChooserUI;
import com.github.org.sparks_of_fabrication.imgstenography.loaders.LoaderSolver;

/**
 *
 * @author petko
 */
public class FileChooser extends javax.swing.JFrame {
    
    private LoaderSolver imageLoader;
   
    private boolean isFileChoserVisible;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FileChooser.class.getName());

    /**
     * Creates new form ImageChooser
     */
    public FileChooser(LoaderSolver loader) {
        initComponents();
        
        this.isFileChoserVisible = false;
        
        imageLoader = loader;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jFileChooser1.setApproveButtonText("Choose Image");
        jFileChooser1.setApproveButtonToolTipText("");
        jFileChooser1.setDialogTitle("Choose image");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        
        if(evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            System.out.println("TEST");
            String filePath = jFileChooser1.getCurrentDirectory().getAbsolutePath();
            File selectedFile = jFileChooser1.getSelectedFile();
            
            boolean error = imageLoader.setFile(this, selectedFile);
            
            if(error) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
