/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.org.sparks_of_fabrication.imgstenography.graphics;

import com.github.org.sparks_of_fabrication.imgstenography.TextInputType;
import com.github.org.sparks_of_fabrication.imgstenography.loaders.ImageLoader;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author petko
 */
public class ImagePanel extends javax.swing.JPanel implements ChildPanel<ImageLoader> {
    
    ImageLoader imageLoader;
    /**
     * Creates new form ImagePanel
     */
    
    public ImagePanel() {
        initComponents();
    }

    @Override
    public void inherit(ImageLoader obj) {
        this.imageLoader = obj;
        
        jLabel1.setText(String.format("Current File Chosen: %s", imageLoader.getFile().getName()));
        jLabel2.setText("");
        
        imagePreview1.setVisible(false);
        jToggleButton1.setEnabled(false);
        
        imagePreview1.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentShown(ComponentEvent e) {
                    if(imageLoader.isTriggered()) {
                        showImagePreview();
                    }
                }

                @Override
                public void componentResized(ComponentEvent e) {
                    if(imageLoader.isTriggered()) {
                          showImagePreview();
                    }
                }
            });
    }
    
    
    private void showImagePreview() {
        Dimension dimension = imageLoader.imageGetDimensions();
        String dimensionText = String.format("width: %d, height: %d",  dimension.width, dimension.height);
        jLabel2.setText(dimensionText);
        BufferedImage file = imageLoader.convertIntoSolver();
        
        imagePreview1.drawImage(file);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        imagePreview1 = new com.github.org.sparks_of_fabrication.imgstenography.graphics.ImagePreview();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("Chose image");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("Preview");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePreview1Layout = new javax.swing.GroupLayout(imagePreview1);
        imagePreview1.setLayout(imagePreview1Layout);
        imagePreview1Layout.setHorizontalGroup(
            imagePreview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        imagePreview1Layout.setVerticalGroup(
            imagePreview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(imagePreview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(imagePreview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        if(jToggleButton1.isSelected()) {
            imagePreview1.setVisible(true);
        }else {
            imagePreview1.setVisible(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:

        FileChooser imgForm = new FileChooser(imageLoader);

        imgForm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if(!imageLoader.getFile().getName().equals("")) {
                    jLabel1.setText(String.format("Current File Chosen: %s", imageLoader.getFile().getName()));
                    jToggleButton1.setEnabled(true);

                    showImagePreview();
                }else{
                    jLabel1.setText(String.format("Current File Chosen: %s", ""));
                    jToggleButton1.setEnabled(false);
                }
            }

        });

        imgForm.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.org.sparks_of_fabrication.imgstenography.graphics.ImagePreview imagePreview1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
