/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.org.sparks_of_fabrication.imgstenography.graphics;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author dobri
 */
public class PSNR_Bar_Graph_Panel extends javax.swing.JPanel {
    private int padding = 15;
    private int width, height;
    private int data[];
    /**
     * Creates new form PSNR_Bar_Graph_Panel
     */
    public PSNR_Bar_Graph_Panel() {
        initComponents();
    }
    
     @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d=(Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        width = this.getWidth();
        height = this.getHeight();
        g2d.drawLine(padding, padding, padding, height-padding);
        g2d.drawLine(padding, height-padding, width-padding, height-padding);
        g2d.drawString("0", padding, height-padding+10);
        
        int max = data[0];
        for(int i = 0; i<data.length; i++){
            if(max<data[i]){
                max=data[i];
            }
        }
        
        double widthCoef = (width - 2*padding)/ (double) data.length;
        double heightCoef = (height - 2*padding)/ (double) max;
       
        g2d.setColor(Color.red);
        for(int i=0; i<data.length; i++){
            g2d.drawRect((int) (padding+i*widthCoef), (int) (height-data[i]*heightCoef-padding), (int) widthCoef, (int) (data[i]*heightCoef));
            g2d.fillRect((int) (padding+i*widthCoef)+1, (int) (height-data[i]*heightCoef-padding)+1, (int) widthCoef-1, (int) (data[i]*heightCoef)-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
